# Generated by Django 5.1.6 on 2025-07-27 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Заглавие на събитието"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("date_time", models.DateTimeField(verbose_name="Дата и час")),
                ("city", models.CharField(max_length=100, verbose_name="Град")),
                (
                    "location_details",
                    models.CharField(
                        max_length=300, verbose_name="Точно местоположение"
                    ),
                ),
                (
                    "is_kid_friendly",
                    models.BooleanField(
                        default=False, verbose_name="Подходящо за деца"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="event_images/",
                        verbose_name="Основна снимка",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(verbose_name="Максимален капацитет"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="registered_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Записани участници",
                    ),
                ),
                (
                    "interests",
                    models.ManyToManyField(
                        related_name="events",
                        to="events.interest",
                        verbose_name="Интереси",
                    ),
                ),
            ],
        ),
    ]
