# Generated by Django 5.1.6 on 2025-07-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_questionnaire_completed"),
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Interest",
        ),
        migrations.AlterField(
            model_name="event",
            name="interests",
            field=models.ManyToManyField(
                related_name="events", to="core.interest", verbose_name="Интереси"
            ),
        ),
    ]
