# Generated by Django 5.1.6 on 2025-07-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_delete_interest_alter_event_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
