# Generated by Django 5.1.6 on 2025-08-24 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_eventregistration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventregistration",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="eventregistration",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Очаква одобрение"),
                    ("approved", "Одобрено"),
                    ("rejected", "Отказано"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="child_age",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="child_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="full_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="eventregistration",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
