# Generated by Django 5.1.6 on 2025-07-22 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("can_travel_to_sofia", models.BooleanField()),
                ("about", models.TextField()),
                ("has_children", models.BooleanField()),
                (
                    "wants_events_with_children",
                    models.BooleanField(blank=True, null=True),
                ),
                ("why_join", models.TextField()),
                ("instagram", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("friend_name", models.CharField(blank=True, max_length=100)),
                ("how_did_you_hear", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("interests", models.ManyToManyField(to="core.interest")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
