# Generated by Django 5.1.6 on 2025-07-22 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_interest_userquestionnaire"),
    ]

    operations = [
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("can_travel_to_sofia", models.BooleanField()),
                ("about", models.TextField()),
                ("has_children", models.BooleanField()),
                ("wants_events_with_children", models.BooleanField()),
                ("why_join", models.TextField()),
                ("instagram", models.CharField(blank=True, max_length=255, null=True)),
                ("tiktok", models.CharField(blank=True, max_length=255, null=True)),
                ("linkedin", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "friend_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("how_did_you_hear", models.CharField(max_length=255)),
                ("interests", models.ManyToManyField(to="core.interest")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="UserQuestionnaire",
        ),
    ]
