# Generated by Django 5.1.6 on 2025-07-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_questionnaire_delete_userquestionnaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionnaire",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
