# Generated by Django 5.1.6 on 2025-08-27 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_customuser_avatar"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_event_reminders",
                    models.BooleanField(
                        default=True,
                        verbose_name="Известия за събития, за които съм записана",
                    ),
                ),
                (
                    "email_event_status_changes",
                    models.BooleanField(
                        default=True,
                        verbose_name="Известия за одобрена/отхвърлена заявка за събитие",
                    ),
                ),
                (
                    "email_recommendations",
                    models.BooleanField(
                        default=True,
                        verbose_name="Известия за събития, подходящи за мен",
                    ),
                ),
                (
                    "email_profile_changes",
                    models.BooleanField(
                        default=True, verbose_name="Известия при промяна на лични данни"
                    ),
                ),
                (
                    "email_questionnaire_changes",
                    models.BooleanField(
                        default=True,
                        verbose_name="Известия при промяна на отговори от въпросника",
                    ),
                ),
                (
                    "email_news",
                    models.BooleanField(
                        default=False,
                        verbose_name="Нови предложения и новини от LuxeLadies",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificationsettings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Потребител",
                    ),
                ),
            ],
        ),
    ]
